// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqjekcdrybwklyotxfha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxamVrY2RyeWJ3a2x5b3R4ZmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTgwNjMsImV4cCI6MjA2NTU5NDA2M30.nwiBSlylD_0gPdCfzGeK2MvQKd6EZzh5fKBHXxdi3e0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);